# Generated by Django 3.2.16 on 2022-11-06 21:57

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('height', models.CharField(max_length=128)),
                ('mass', models.CharField(max_length=128)),
                ('hair_color', models.CharField(max_length=128)),
                ('skin_color', models.CharField(max_length=128)),
                ('eye_color', models.CharField(max_length=128)),
                ('birth_year', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=128)),
                ('homeworld', models.CharField(max_length=128)),
                ('films', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('species', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('vehicles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('starships', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('created', models.CharField(max_length=128)),
                ('edited', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('data_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='people.dataset')),
            ],
        ),
    ]
